.TH CHECKSTYLE-REPORTS-COMBINER 1 2020-03-06

.SH NAME
checkstyle-reports-combiner \- Combine Checkstyle XML reports from two and more

.SH SYNOPSIS
.B checkstyle-reports-combiner
[\fB\-\-operator=\fR{\fBunion\fR|\fBintersect\fR|\fBexcept\fR}]
[\fB\-\-all\fR]
[\fB\-\-file-key=\file-key\fR]
[\fB\-\-result-key=\result-key\fR]
[\fB\-\-namespace=\fIname\fB=\fIuri\fR \fI...\fR]
.I file
[\fI...\fR]

.SH DESCRIPTION
The reports of two and more can be combined using the set operations union, intersection, and difference.
The command reads files sequentially, writing them to the standard output.
The file operands are processed in command-line order.
If there are fewer than two file operands, this command reads from the standard input.
.SS UNION
The UNION operation combines the results of two reports into a single result that comprises the elements that are returned by both reports.
.SS INTERSECT
The INTERSECT operation combines the reports of two into a single result that comprises all the elements common to both reports.
.SS EXCEPT
The EXCEPT operation finds the difference between the two reports and the result comprises the element that belong only to the first report.

.SH OPTIONS
.PP
.PD 0
.TP
.B \-\-operator=union
.PD 0
.TP 
.B \-\-operator=intersect
.PD 0
.TP
.B \-\-operator=except
Specify an operator. Default is \fBunion\fR.
.TP
.B \-\-all
Duplicate elements are eliminated unless \fB\-\-all\fR is used.
.TP
\fB\-\-file-key=\fIfile-key\fR
Specify an XPath expression that uniquely identifies the \fB<file>\fR element. Default is \fBstring(@name)\fR.
.TP
\fB\-\-result-key=\fIresult-key\fR
Specify an XPath expression that uniquely identifies the \fB<error>\fR element or \fB<exception>\fR element. Default is \fBstring(.)\fR.

.SH EXAMPLES
Combines two reports:
.nf

    checkstyle-reports-combiner TEST-example.FooTest.xml TEST-example.BarTest.xml

.fi
Shows the differences between the two reports:
.nf

    checkstyle-reports-combiner --operator=except TEST-example.FooTest-1.xml TEST-example.FooTest-2.xml

.fi
